#!/bin/bash

set -euo pipefail

TITLE="$1"
PROCESSED_TITLE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]'| sed -e "s/ /\-/g")
FILENAME="_posts/$(date '+%Y-%m-%d')-$PROCESSED_TITLE.md"

cat _drafts/format.md | sed -e "s#<title-goes-here>#$TITLE#g" >$FILENAME
